export const pokemonTypes = {
  normal: {
    name: "Normal",
    immunes: ["Ghost"],
    weaknesses: ["Rock", "Steel"],
    strengths: [],
    color: "#A8A77A",
  },
  fire: {
    name: "Fire",
    immunes: [],
    weaknesses: ["Fire", "Water", "Rock", "Dragon"],
    strengths: ["Grass", "Ice", "Bug", "Steel"],
    color: "#EE8130",
  },
  water: {
    name: "Water",
    immunes: [],
    weaknesses: ["Water", "Grass", "Dragon"],
    strengths: ["Fire", "Ground", "Rock"],
    color: "#6390F0",
  },
  electric: {
    name: "Electric",
    immunes: ["Ground"],
    weaknesses: ["Electric", "Grass", "Dragon"],
    strengths: ["Water", "Flying"],
    color: "#F7D02C",
  },
  grass: {
    name: "Grass",
    immunes: [],
    weaknesses: ["Fire", "Grass", "Poison", "Flying", "Bug", "Dragon", "Steel"],
    strengths: ["Water", "Ground", "Rock"],
    color: "#7AC74C",
  },
  ice: {
    name: "Ice",
    immunes: [],
    weaknesses: ["Fire", "Water", "Ice", "Steel"],
    strengths: ["Grass", "Ground", "Flying", "Dragon"],
    color: "#96D9D6",
  },
  fighting: {
    name: "Fighting",
    immunes: ["Ghost"],
    weaknesses: ["Poison", "Flying", "Psychic", "Bug", "Fairy"],
    strengths: ["Normal", "Ice", "Rock", "Dark", "Steel"],
    color: "#C22E28",
  },
  poison: {
    name: "Poison",
    immunes: ["Steel"],
    weaknesses: ["Poison", "Ground", "Rock", "Ghost"],
    strengths: ["Grass", "Fairy"],
    color: "#A33EA1",
  },
  ground: {
    name: "Ground",
    immunes: ["Flying"],
    weaknesses: ["Grass", "Bug"],
    strengths: ["Fire", "Electric", "Poison", "Rock", "Steel"],
    color: "#E2BF65",
  },
  flying: {
    name: "Flying",
    immunes: [],
    weaknesses: ["Electric", "Rock", "Steel"],
    strengths: ["Grass", "Fighting", "Bug"],
    color: "#A98FF3",
  },
  psychic: {
    name: "Psychic",
    immunes: ["Dark"],
    weaknesses: ["Psychic", "Steel"],
    strengths: ["Fighting", "Poison"],
    color: "#F95587",
  },
  bug: {
    name: "Bug",
    immunes: [],
    weaknesses: [
      "Fire",
      "Fighting",
      "Poison",
      "Flying",
      "Ghost",
      "Steel",
      "Fairy",
    ],
    strengths: ["Grass", "Psychic", "Dark"],
    color: "#A6B91A",
  },
  rock: {
    name: "Rock",
    immunes: [],
    weaknesses: ["Fighting", "Ground", "Steel"],
    strengths: ["Fire", "Ice", "Flying", "Bug"],
    color: "#B6A136",
  },
  ghost: {
    name: "Ghost",
    immunes: ["Normal"],
    weaknesses: ["Dark"],
    strengths: ["Psychic", "Ghost"],
    color: "#735797",
  },
  dragon: {
    name: "Dragon",
    immunes: ["Fairy"],
    weaknesses: ["Steel"],
    strengths: ["Dragon"],
    color: "#6F35FC",
  },
  dark: {
    name: "Dark",
    immunes: [],
    weaknesses: ["Fighting", "Dark", "Fairy"],
    strengths: ["Psychic", "Ghost"],
    color: "#705746",
  },
  steel: {
    name: "Steel",
    immunes: [],
    weaknesses: ["Fire", "Water", "Electric", "Steel"],
    strengths: ["Ice", "Rock", "Fairy"],
    color: "#B7B7CE",
  },
  fairy: {
    name: "Fairy",
    immunes: [],
    weaknesses: ["Fire", "Poison", "Steel"],
    strengths: ["Fighting", "Dragon", "Dark"],
    color: "#B7B7CE",
  },
};
